/// Flutter icons OwnIcons
/// Copyright (C) 2026 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OwnIcons
///      fonts:
///       - asset: fonts/OwnIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class OwnIcons {
  OwnIcons._();

  static const _kFontFam = 'OwnIcons';
  static const String? _kFontPkg = null;

  static const IconData cancellation_rate_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData about_us_icon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bathrooms_icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bedrooms_icon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beds_icon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blogs_icon = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData venture_icon = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_icon = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData co_host_control_icon = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact_support_icon = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy_icon = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cross_icon = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_icon = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData education_icon = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emoji_icon = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData face_verification = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favourite_icon = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_icon = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData downarrow_icon = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox_icon_for_guest = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData go_next_icon = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_icon_for_guest = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData guests_icon = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trip_icon_filled = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_1_icon = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trip_icon_outlined = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_2_icon = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData payout_method_icon = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_icon = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quick_replies_icon = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refer_host_icon = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reservation_icon = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_arrow_icon = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_icon = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send_icon = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_icon = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_recommendation_icon = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData specialized_icon = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData start_icon = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData super_host_icon = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData switch_icon = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData take_photo_icon = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData terms_and_condition_icon = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData today_icon = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unsend_icon = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uparrow_icon = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload_photo_icon = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData where_live_in_icon = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData work_icon = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData response_time_icon = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hosted_successfull_icon = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData review_icon = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visibility_icon = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_icon = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_icon = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leftarrow_icon = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calender_icon = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData finance_icon = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData today_icon_outlined = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

// Hello I am Tamim